### PR TITLE
locationloading

### LINKED ISSUE #82: [BUG] - locationLoading State Hangs on Permission Denial
### Description

When a user denies location permissions via the system prompt, the locationLoading state remains true indefinitely. This prevents the loading overlay from dismissing, effectively soft-locking the application.

### Reproduction steps

```bash
1. Ensure the app’s location permission is set to "Ask Next Time"
2. Launch the app on a fresh install
3. Trigger the useCurrentLocation hook logic by selecting the location tab on the navbar
4. When the system permission dialog appears ("Allow [App] to access your location?"), select "Don't Allow" (Deny).
5. Observe that the loading spinner remains on screen.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash

```

### Browsers

_No response_

### OS

Mac

### PR DESCRIPTION
**Pull request by Kerryki**
This pull request improves the handling of location permission denial in the `useCurrentLocation` hook and adds a new test to verify this behavior. The main focus is ensuring that the loading state is properly cleared if the user denies location permission while the component is unmounted (such as when the app is backgrounded).

**Testing improvements:**

* Added a test to `useCurrentLocation-test.ts` that verifies the loading state is cleared and no attempt is made to get the current position if permission is denied after the component has unmounted.

**Hook logic improvements:**

* Updated `useCurrentLocation.ts` to always clear the loading state when location permission is denied, even if the component has unmounted while the permission dialog is open.
* Adjusted the order of the `isMounted` check to ensure the denial branch runs and state is cleared before returning early due to unmounting.

### CODE REVIEW

**Review by Shamsam — APPROVED** [review]
Great work. Nice and easy fix.

File: mobile/__tests__/hooks/useCurrentLocation-test.ts [hunk 1]
```diff
@@ -135,6 +135,29 @@ describe("useCurrentLocation", () => {
...
+          resolvePermission = resolve;
+        }),
+    );
+
+    const { unmount } = renderHook(() => useCurrentLocation());
+
+    // Simulate app going to background while dialog is open
+    unmount();
+
+    // User taps "Don't Allow" — the denial branch must run (no early isMounted
```
Comment (NNLNoah) [inline mobile/__tests__/hooks/useCurrentLocation-test.ts:152]: nice comments

**Review by NNLNoah — APPROVED** [review]
Nice, short PR. As it should be
